# _targets.R
library(targets)
library(jagstargets)
library(mgcv)

# example from mgcv::jagam

# data generation process
generate_data <- function(n = 400) {
  dat <- gamSim(1,n=n,dist="normal",scale=2, verbose=FALSE)
  data.frame(x2 = dat$x2, y = dat$f2+rnorm(n, 0,2))
}

# function to take output from generate_data() and make a list for JAGS
jagsify_data <- function(dat) {
  list(n = nrow(dat), x2 = dat$x2, y = dat$y)
}

# get the design matrix, using mgcv::jagam(), not very efficient!
jagsify <- function(dat){
  # ignoring the autogenerated file here
  jagam(y~s(x2), data=dat, file="jagam_tmp.jags",
        sp.prior="gamma", diagonalize=TRUE)
}

# combine the design matrix and other data for JAGS
combine_jags_dat <- function(data, jagam_model){
  c(data, list(X=jagam_model$jags.data$X))
}

## regular gam fit for comparison...
fit_gam <- function(dat){
  dat <- as.data.frame(dat)
  b0 <- gam(y~s(x2), select=TRUE, data=dat, method="REML")
  # just return the effective degrees of freedom for the model
  list(edf=sum(b0$edf))
}

# postprocessing for jagam model
jagam_postprocess <- function(samples, jagam_model){
  # this is not a tidy area!
  samples$deviance <- NULL
  samples$.chain <- NULL
  samples$.draw <- NULL
  samples$.iteration <- NULL

  # sim2jam expects a mcsample object, we need to fake that...
  rho <- t(as.matrix(samples[, grepl("^rho", colnames(samples))]))
  rho <- array(rho, dim=c(nrow(rho), ncol(rho), 1))
  b <- t(as.matrix(samples[, grepl("^b", colnames(samples))]))
  b <- array(b, dim=c(nrow(b), ncol(b), 1))
  # yiiiikes
  sam <- list(b=b, rho=rho)
  # use EDF type 1 for comparison with mgcv::gam()
  jam <- sim2jam(sam, jagam_model$pregam, edf.type=1)
  # get total EDF for the model
  list(edf=sum(jam$edf))
}

list(
  tar_target(simdat, generate_data()),
  tar_target(simmod, jagsify(simdat)),
  tar_target(jagsdat, jagsify_data(simdat)),
  tar_target(combine_jags, combine_jags_dat(jagsdat, simmod)),
  tar_jags(
    jagsfit,
    jags_files = "jagam.jags",
    parameters.to.save = c("b", "rho"),
    data = combine_jags,
    stdout = R.utils::nullfile(),
    stderr = R.utils::nullfile(),
  ),
  tar_target(mgcvfit, fit_gam(simdat)),
  tar_target(jagam_post, jagam_postprocess(jagsfit_draws_jagam, simmod))
)



